### ISSUE TITLE
Questions About this

### ISSUE THREAD

**Issue by Akul2010** [Imira-S-R/PasswordManager#2]
Hi, I was really impressed with your work, being a beginner myself. I wanted to ask a few things, though. 

1. Can I use this as a template to make my own password manager?
2. Is it secure?

Thanks!

**Comment by Imira-S-R** [comment]
Hello 👋 @Akul2010 

1. Can I use this as a template to make my own password manager?
Yes you can use this as a template to make your own password manager.

2. is it secure ?
Yes. I have added encryption to the app, so it will encrypt all the data entered by the user before it is stored in the database.
I will also in the future add more security features like login timeouts to the app.

Hope I answered your questions, 
Imira
